# Change these first
owner: remotecheckin # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: Website
    url: https://www.remotecheckin.co.uk
  - name: Test01
    url: https://app.remotecheckin.co.uk/Check_in?SiteID=Test01
    __dangerous__body_down: "OFFLINE"
  - name: Test02
    url: https://app.remotecheckin.co.uk/Check_in?SiteID=Test02
    __dangerous__body_down: "OFFLINE"
  - name: FBTest
    url: https://app.remotecheckin.co.uk/Check_in?SiteID=FBTest
    __dangerous__body_down: "OFFLINE"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://monitor.remotecheckin.co.uk
  # baseUrl: /monitor
  logoUrl: https://www.remotecheckin.co.uk/assets/images/LogoH_P.svg
  name: monitor
  introTitle: "Welcome to the Remote Check In Status Page."
  introMessage: This page should list all sites to check their active status.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
